# -*- coding: utf-8 -*-
"""Gemini_Sinhala_Corrector_V3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qknq1ArNuPJIrbd29s6z_vyKWBc2EGGs
"""

# IDE / local setup:
# Run this one time in your terminal before running this file:
#   pip install google-generativeai

import time
import re
import google.generativeai as genai

API_KEY = "AIzaSyAbGXod1bKxlFlh-pAmShuouA48miqoiQk"

genai.configure(api_key=API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")

print("Gemini ready ✅")

def clean_output(text):
    text = text.strip()
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL)
    text = text.replace("Corrected output:", "")
    text = text.replace("Corrected Sinhala:", "")
    text = text.replace("Improved corrected Sinhala:", "")
    text = text.replace("Final corrected Sinhala:", "")
    text = text.replace("Corrected:", "")
    text = text.replace("corrected:", "")
    return text.strip()

def split_text(text, max_chars=1500):
    words = text.split()
    chunks = []
    current = ""

    for word in words:
        if len(current) + len(word) + 1 <= max_chars:
            current += word + " "
        else:
            chunks.append(current.strip())
            current = word + " "

    if current.strip():
        chunks.append(current.strip())

    return chunks

FIRST_PASS_PROMPT = """\
You are an expert Sinhala text correction engine. Your job is to take noisy, poorly \
typed, or speech-to-text Sinhala text and return clean, natural, grammatically correct \
Sinhala — while keeping the original meaning and colloquial spoken style.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WHAT YOU MUST FIX
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. SPELLING ERRORS — fix wrong Sinhala character combinations and phonetic misspellings.
2. BROKEN WORDS — words split into pieces must be joined back.
   e.g. "කර නවා" → "කරනවා",  "ගෙවන් නේ" → "ගෙවන්නේ"
3. JOINED WORDS — words accidentally merged must be split.
   e.g. "ටීවීසහ" → "ටීවී සහ",  "නැහැගැටලුවක්" → "නැහැ. ගැටලුවක්"
4. MISSING OR WRONG VOWEL SIGNS — restore correct Sinhala vowel diacritics.
5. PHONETICALLY SPELLED NUMBERS — convert to standard written form.
   e.g. "දෙදාස් පන්සේ" → "දෙදහස් පන්සිය",  "අසු ගාණක්" → "අසූවක්"
6. MISSING PUNCTUATION — add full stops, commas, question marks where clearly needed.
7. GRAMMAR — fix verb endings, particle agreement, and word order if broken.
8. LOANWORDS IN SINHALA SCRIPT — keep them as-is, just fix any script errors.
   e.g. ටීවී, වොයිස්, ලයින්, බොක්ස්, ෆික්ස්, ඔන්, ඔෆ්, කේබල්, රිමෝට්, පැකේජ්

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Keep ALL sentences. Do NOT remove or skip anything.
- Do NOT summarize, paraphrase beyond correction, or change the meaning.
- Keep the tone natural and spoken — not overly formal.
- Do NOT translate to English.
- Do NOT convert payment/amount phrases into phone numbers, IDs, or account numbers
  unless the input clearly says so. If context is about paying (ගෙවන්න තියෙනවා),
  treat nearby distorted number words as an amount.
- Output ONLY the corrected Sinhala text — no labels, no explanations.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXAMPLES  (these show PATTERNS — not words to memorize)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

--- Pattern: fixing joined words + missing spaces ---
NOISY:   අද උදේටත් ඔෆිස්එකට ගිහින්ලොකුකතාවක් කෙරුවා
FIXED:   අද උදේටත් ඔෆිස් එකට ගිහින් ලොකු කතාවක් කෙරුවා.

--- Pattern: fixing broken/split words ---
NOISY:   ඒ කො ම්පැනිය ගා නු දෙ න්නේ නෑ ලු
FIXED:   ඒ කොම්පැනිය ගාණු දෙන්නේ නෑ ලු.

--- Pattern: phonetic spelling + missing punctuation ---
NOISY:   මෙ ගෙදරත් ගෑස් නෑ ඉතිං කං කරන්නේ කො හොමදෝ
FIXED:   මේ ගෙදරත් ගෑස් නෑ. ඉතින් කන්නේ කොහොමද?

--- Pattern: phonetically written numbers near payment context ---
NOISY:   බිල් එකේ එකදාස් හාරැසේ ගාව ගෙවන්නොන
FIXED:   බිල් එකේ එක් දහස් හාරසිය ගාව ගෙවන්නොනේ.

--- Pattern: colloquial speech with wrong vowels + loanwords ---
NOISY:   ගිහිල්ල බැලව ඒකෙ ස්විට් ශ් එක ඔෆ් කරලා ආවෝ ගැලෙව
FIXED:   ගිහිල්ල බැලුවා, ඒකේ ස්විච් එක ඔෆ් කරලා ආවා. ගැලවිලා.

--- Pattern: very garbled input, keep all content ---
NOISY:   ඒකල නනෙවෙ හරිය ඒ ගා නක් ගෙවන්නේ නෑ ඔකො ලො ට
FIXED:   ඒ කළ නැනේ, හරිය ඒ ගාණක් ගෙවන්නේ නෑ ඔකොළොට.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Now correct the following noisy Sinhala text:

Text:
{text}

Corrected Sinhala:
"""


def correct_sinhala_text(text):
    prompt = FIRST_PASS_PROMPT.format(text=text)

    response = model.generate_content(
        prompt,
        generation_config={
            "temperature": 0.1,
            "top_p": 0.75,
            "top_k": 30,
            "max_output_tokens": 8192
        }
    )

    return clean_output(response.text)

def process_text(text, max_chars=1500, retries=3, delay_between_chunks=1):
    chunks = split_text(text, max_chars=max_chars)
    results = []

    print(f"Total chunks: {len(chunks)}\n")

    for i, chunk in enumerate(chunks):
        print(f"Processing chunk {i+1}/{len(chunks)}...")

        success = False

        for retry in range(retries):
            try:
                output = correct_sinhala_text(chunk)

                if len(output) < len(chunk) * 0.65:
                    print("Output seems incomplete. Retrying...")
                    time.sleep(3)
                    continue

                results.append(output)
                success = True
                break

            except Exception as e:
                print(f"Retry {retry+1}/{retries}: {e}")
                time.sleep(3 * (retry + 1))

        if not success:
            print("Chunk failed. Keeping original chunk.")
            results.append(chunk)

        time.sleep(delay_between_chunks)

    return " ".join(results)

VERIFY_PROMPT = """\
You are a Sinhala correction reviewer.

You will receive:
1. Original noisy Sinhala text
2. First corrected version

Your task:
Improve the corrected version by fixing anything that was missed or still looks unnatural.

Focus especially on:
- Distorted number or payment phrases that are still wrong
- Broken sentence endings or missing punctuation
- Parts copied from the noisy input without correction
- Sinhala words that sound similar but were written incorrectly
- Overall sentence flow and naturalness
- Loanwords in Sinhala script (ටීවී, වොයිස්, ලයින්, බොක්ස්, ෆික්ස්, etc.) — keep them, just fix script errors

Rules:
- Compare carefully with the original.
- Reconstruct unclear phrases when context strongly supports the meaning.
- Do not leave noisy fragments unchanged.
- Do not invent unrelated information.
- Do not summarize. Keep the full meaning.
- Keep the tone natural and spoken — not overly formal.
- Output ONLY the final corrected Sinhala text — no labels, no explanations.

Original noisy text:
{original}

First corrected version:
{corrected}

Final corrected Sinhala:
"""


def verify_and_fix(original_text, corrected_text):
    prompt = VERIFY_PROMPT.format(original=original_text, corrected=corrected_text)

    response = model.generate_content(
        prompt,
        generation_config={
            "temperature": 0.15,
            "top_p": 0.8,
            "top_k": 30,
            "max_output_tokens": 16384
        }
    )

    return clean_output(response.text)


if __name__ == "__main__":

    noisy_text = """රනගසරට සෞදින් හඩ දැනට කනෙක්ෂණ එක බෙල්පත නිසා දිස්කනක්වලාතිනනේ දැනටව නොවෙඹ කාල සනොවෙබ තිහොදක්වා රුපියල් දහ තුන්දා සාරසිය හැටට දකකෂතැහැට දෙක කොමතල ියෙනවා බිල්පපඊමිලසරහා සෙන්කරන්නේ ිසම්බ විසිදෙක තමයි ඩූඩේටෙක තිබිලා තියෙන නොවෙම්බ බිහටත් පේමට් ික කරත් කනෙක්ෂන් ටික ඔටෝමටික ටික වෙලාවකින් ඇත්ූවෙනවාේන් එකක් රලතියමැඩම් පේමන්ට් ිකක් කරලා තියෙන්නේ දිේබ විසිහට අට දාක්ිට පස්සේ ේමනට් එකක් කරතාමණං අභිටතුලා නෑ පේ කරපු මවන් එක කියද කයල දැනගන්න පුළුවන්ද මැඩ ්මට ඩීටෙල්ස් ටික දෙන්න පොළොන් අනුලින්ද කොොම්ද පේම්ික කරේබැංක කමුට් එකෙන් මැඩම්ගේ මවුන් එක දිඩක් තනාද නකන්ටාන්සික්ෂණත න්සික්ෂණ රිෆරන්ටස් නම් එකත් මැඩම් ලබා ගත්අදඔහුවෝ බෑන්ක් එක් අවුන්ට කේන එක අරිමං එමුනත් කමතෙන එකත් දානමට පේකරපු වෙලාව කියන්නනම්පොඩකින්"""


    first_pass = process_text(
        noisy_text,
        max_chars=1500,
        retries=3,
        delay_between_chunks=1
    )

    print("\n===== FIRST PASS OUTPUT =====\n")
    print(first_pass)

    final_output = verify_and_fix(noisy_text, first_pass)

    print("\n===== FINAL OUTPUT =====\n")
    print(final_output)
